### ISSUE TITLE
warningがあってもコンパイルが通ってしまう

### ISSUE THREAD

**Issue by dodo5522** [keinarita19891004/LanguageToSufferInCLanguage#3]
gccのオプションに `-Werror` を追加しましょう。

**Comment by K-Nari04** [comment]
すみません、こちらはtask.jsonの"args"の中に追記すればよろしいのでしょうか、、？

**Comment by dodo5522** [comment]
こちらのissueの前に #2 を片付けましょう！
各オプションの意味は調べてみてください。

> args

まずは試して実行して、追加する前後でコンパイル動作がどのように変わるか試してみましょう。
try and errorを繰り返すのもいい勉強になります。

**Comment by dodo5522** [comment]
こちらの設定も追加されていないようです。ご対応お願いします。

**Comment by dodo5522** [comment]
対応していただいたのでclose
https://github.com/keinarita19891004/LanguageToSufferInCLanguage/commit/dc0773322c4e0b8df2f9c918745febbbbe2c29b7
